export const ADICIONA_CLIENTE = "ADICIONA_CLIENTE";
export const ALTERA_CLIENTE = "ALTERA_CLIENTE";
export const EXCLUI_CLIENTE = "EXCLUI_CLIENTE";
export const BUSCA_CLIENTE = "BUSCA_CLIENTE";
export const LIMPA_LISTA = "LIMPA_LISTA";
export const DEFINE_CLIENTE = "DEFINE_CLIENTE";
export const DEFINE_CLIENTES = "DEFINE_CLIENTES";
export const BUSCA_CLIENTE_ID = "BUSCA_CLIENTE_ID";
export const ATUALIZA_CLIENTE = "ATUALIZA_CLIENTE";
export const EDITA_CLIENTE = "EDITA_CLIENTE";

export const ALTERA_TABS = "ALTERA_TABS";
export const DEFINE_TABS = "DEFINE_TABS";

export const LIMPA_LISTA_DOCS = "LIMPA_LISTA_DOCS";
export const DEFINE_DOCUMENTOS = "DEFINE_DOCUMENTOS";
export const ADICIONA_DOCUMENTO = "ADICIONA_DOCUMENTO";
export const REMOVE_DOCUMENTO = "REMOVE_DOCUMENTO";

export const LIMPA_LISTA_REFS = "LIMPA_LISTA_REFS";
export const DEFINE_REFERENCIAS = "DEFINE_REFERENCIAS";
export const ADICIONA_REFERENCIA = "ADICIONA_REFERENCIA";
export const REMOVE_REFERENCIA = "REMOVE_REFERENCIA";

export const TO_EDIT_CLIENT = "TO_EDIT_CLIENT";

export const NOTIFICA = "NOTIFICA";
