export const ADICIONAR_CLIENTE = "ADICIONAR_CLIENTE";
export const ALTERAR_CLIENTE = "ALTERAR_CLIENTE";
export const EXCLUIR_CLIENTE = "EXCLUIR_CLIENTE";
export const BUSCAR_CLIENTE = "BUSCAR_CLIENTE";
export const LIMPAR_LISTA_CLI = "LIMPAR_LISTA_CLI";
export const DEFINIR_CLIENTE = "DEFINIR_CLIENTE";
export const DEFINIR_CLIENTES = "DEFINIR_CLIENTES";
export const BUSCAR_CLIENTE_ID = "BUSCAR_CLIENTE_ID";
export const ATUALIZAR_CLIENTE = "ATUALIZAR_CLIENTE";
export const EDITAR_CLIENTE = "EDITAR_CLIENTE";

export const ALTERAR_TABS = "ALTERAR_TABS";
export const DEFINIR_TABS = "DEFINIR_TABS";

export const DEFINIR_DOCUMENTOS = "DEFINIR_DOCUMENTOS";
export const LIMPAR_LISTA_DOCS = "LIMPA_LISTA_DOCS";
export const ADICIONAR_DOCUMENTO = "ADICIONAR_DOCUMENTO";
export const REMOVER_DOCUMENTO = "REMOVER_DOCUMENTO";

export const DEFINIR_REFERENCIAS = "DEFINIR_REFERENCIAS";
export const LIMPAR_LISTA_REFS = "LIMPAR_LISTA_REFS";
export const ADICIONAR_REFERENCIA = "ADICIONAR_REFERENCIA";
export const REMOVER_REFERENCIA = "REMOVER_REFERENCIA";

export const NOTIFICAR = "NOTIFICAR";
