export const ADICIONA_CLIENTE = 'ADICIONA_CLIENTE'
export const ALTERA_CLIENTE = 'ALTERA_CLIENTE'
export const EXCLUIR_CLIENTE = 'EXCLUIR_CLIENTE'
export const BUSCAR_CLIENTE = 'BUSCAR_CLIENTE'
export const LIMPAR_LISTA = 'LIMPAR_LISTA'

export const NOTIFICAR = 'NOTIFICAR'
